- name: install apache2
  apt: name=apache2 state=present

- name: update apache2 config
  copy: src=apache2.conf dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache2

- name: update apache2 envvars
  copy: src=apache2_envvars dest=/etc/apache2/envvars
  notify: restart apache2

- name: install git early
  apt: name={{ item }}
  with_items:
    - curl
    - man
    - git

- name: add brightbox and ansible ppa
  apt_repository:  repo={{item}}
  with_items:
    - ppa:brightbox/ruby-ng

- name: install bash-completion and paramiko (for helpers)
  apt: name={{ item }}
  with_items:
    - bash-completion
    - python-paramiko
    - python-dev
    - python-pip

- name: install paramiko version 1.16
  command: pip install paramiko==1.16

- name: run apt-get update
  apt: update_cache=yes

- name: install cldemo base packages 1
  apt: name={{ item }}
  with_items:
    - ruby2.1
    - ruby2.1-dev
    - ruby-switch
    - bundler

- name: set default ruby to 2.1
  command: ruby-switch --set ruby2.1

- name: copy ansible user authorized_keys to cumulus user ssh authorized_keys. needed for prepare_cumulus_env role
  command: cp {{ ansible_env.PWD }}/.ssh/authorized_keys /home/cumulus/.ssh/authorized_keys

- name: put rename script in /var/www
  copy: src=rename_eth_swp dest=/var/www/rename_eth_swp
